// @ts-check

/**
 * Repository module for minify css.test.
 * @module
 */
import { test, expect, describe } from "bun:test";
import { minifyCSS } from "../src/generators/minify-css.js";
describe("minifyCSS", () => {
  test("strips comments", () => {
    expect(minifyCSS("/* hello */ a { color: red; }")).toBe("a{color:red}");
  });
  test("strips multi-line comments", () => {
    const input = `
/* Brand palette
   generated by @sig-ui/cli */
:root { --x: 1; }
`;
    expect(minifyCSS(input)).toBe(":root{--x:1}");
  });
  test("collapses whitespace", () => {
    expect(minifyCSS(`:root {
  --x: 1;
  --y: 2;
}`)).toBe(":root{--x:1;--y:2}");
  });
  test("removes space around braces and semicolons", () => {
    expect(minifyCSS(":root { --x: 1; }")).toBe(":root{--x:1}");
  });
  test("removes space after colons", () => {
    expect(minifyCSS("a{color: red}")).toBe("a{color:red}");
  });
  test("removes space after commas", () => {
    expect(minifyCSS("a{box-shadow: 0 0 0 rgba(0, 0, 0, 0.1)}")).toBe("a{box-shadow:0 0 0 rgba(0,0,0,0.1)}");
  });
  test("removes trailing semicolons before closing brace", () => {
    expect(minifyCSS("a{color:red;}")).toBe("a{color:red}");
  });
  test("shortens 6-digit hex to 3-digit when possible", () => {
    expect(minifyCSS("a{color:#ffffff}")).toBe("a{color:#fff}");
    expect(minifyCSS("a{color:#aabbcc}")).toBe("a{color:#abc}");
    expect(minifyCSS("a{color:#112233}")).toBe("a{color:#123}");
  });
  test("does not shorten non-repeating hex", () => {
    expect(minifyCSS("a{color:#f0f0f0}")).toBe("a{color:#f0f0f0}");
    expect(minifyCSS("a{color:#123456}")).toBe("a{color:#123456}");
  });
  test("does not shorten 8-digit hex (with alpha)", () => {
    expect(minifyCSS("a{color:#ffffff00}")).toBe("a{color:#ffffff00}");
  });
  test("shortens zero values with units", () => {
    expect(minifyCSS("a{margin:0px}")).toBe("a{margin:0}");
    expect(minifyCSS("a{margin:0rem}")).toBe("a{margin:0}");
    expect(minifyCSS("a{margin:0em}")).toBe("a{margin:0}");
  });
  test("does not shorten non-zero values", () => {
    expect(minifyCSS("a{margin:10px}")).toBe("a{margin:10px}");
    expect(minifyCSS("a{margin:1rem}")).toBe("a{margin:1rem}");
  });
  test("handles nested CSS rules", () => {
    const input = `:root {
  --x: 1;
  @supports (color: oklch(0 0 0)) {
    --y: oklch(0.5 0.1 200);
  }
  @media (prefers-color-scheme: dark) {
    --x: 2;
  }
}`;
    const result = minifyCSS(input);
    expect(result).toContain("@supports (color:oklch(0 0 0))");
    expect(result).toContain("@media (prefers-color-scheme:dark)");
    expect(result).toContain("--y:oklch(0.5 0.1 200)");
  });
  test("preserves @layer structure", () => {
    const input = "@layer sigui.tokens { :root { --x: 1; } }";
    expect(minifyCSS(input)).toBe("@layer sigui.tokens{:root{--x:1}}");
  });
  test("combined techniques produce valid output", () => {
    const input = `
/* Generated by @sig-ui/cli */
@layer sigui.tokens {
  :root {
    --brand-500: #6366f1;
    --sg-radius-none: 0px;
    --sg-color-bg-primary: #ffffff;
    box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.05);
  }
}
`;
    const result = minifyCSS(input);
    expect(result).not.toContain("/*");
    expect(result).not.toContain(`
`);
    expect(result).toContain("--brand-500:#6366f1");
    expect(result).toContain("--sg-radius-none:0");
    expect(result).toContain("--sg-color-bg-primary:#fff");
    expect(result).toContain("rgba(0,0,0,0.05)");
  });
  test("empty input returns empty string", () => {
    expect(minifyCSS("")).toBe("");
    expect(minifyCSS("   ")).toBe("");
  });
  test("comment-only input returns empty string", () => {
    expect(minifyCSS("/* only a comment */")).toBe("");
  });
});
