// @ts-check

/**
 * SigUI CLI generators module for typescript.
 * @module
 */
import { DEFAULT_CONFIG } from "@sig-ui/theme";
import {
  generatePalette,
  generateTypeScale,
  computeLineHeight,
  computeLetterSpacing,
  getFontWeights,
  measureTokens,
  generateSpacingScale,
  generateShadowScale,
  getDurationScale,
  getEasingCurves,
  easingToCss,
  getBorderRadiusScale,
  getBorderScale,
  getZIndexScale,
  getMinTouchTarget,
  getFocusRingConfig,
  getStateLayerConfig,
  fromOklch
} from "@sig-ui/core";
const LIGHT_BG = "#ffffff";
const SHADE_STOPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
function safeKey(key) {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `"${key}"`;
}
/**
 * generateTypeScriptTokens.
 * @param {SiguiConfig} config
 * @returns {string}
 */
export function generateTypeScriptTokens(config) {
  const lines = [];
  lines.push("/** Auto-generated by @sig-ui/cli - do not edit */");
  lines.push("");
  const brandPalette = generatePalette(config.brand, { background: LIGHT_BG });
  lines.push("export const brand = {");
  for (const stop of SHADE_STOPS) {
    const color = brandPalette.ramp[stop];
    if (color)
      lines.push(`  ${stop}: "${fromOklch(color, "hex")}",`);
  }
  lines.push("} as const;");
  lines.push("");
  const roles = { ...DEFAULT_CONFIG.roles, ...config.roles };
  for (const [role, hex] of Object.entries(roles)) {
    if (!hex)
      continue;
    const palette = generatePalette(hex, { background: LIGHT_BG });
    lines.push(`export const ${role} = {`);
    for (const stop of SHADE_STOPS) {
      const color = palette.ramp[stop];
      if (color)
        lines.push(`  ${stop}: "${fromOklch(color, "hex")}",`);
    }
    lines.push("} as const;");
    lines.push("");
  }
  const typoOpts = { ...DEFAULT_CONFIG.typography, ...config.typography };
  const typeScale = generateTypeScale({ base: typoOpts.base, ratio: typoOpts.ratio });
  const scaleKeys = ["2xs", "xs", "sm", "base", "lg", "xl", "2xl", "3xl", "4xl", "5xl", "6xl", "7xl", "8xl", "9xl"];
  lines.push("export const typography = {");
  lines.push(`  fontFamily: "${typoOpts.fontFamily}",`);
  lines.push(`  monoFontFamily: "${typoOpts.monoFontFamily}",`);
  for (const step of scaleKeys) {
    const key = step.replace(/^(\d)/, "_$1");
    lines.push(`  "${step}": { fontSize: "${typeScale[step]}rem", lineHeight: "${computeLineHeight(typeScale[step] * 16).computed}", letterSpacing: "${computeLetterSpacing(typeScale[step] * 16).em}em" },`);
  }
  lines.push("} as const;");
  lines.push("");
  const fontWeights = getFontWeights();
  lines.push("export const fontWeights = {");
  for (const [name, weight] of Object.entries(fontWeights)) {
    lines.push(`  ${safeKey(name)}: ${weight},`);
  }
  lines.push("} as const;");
  lines.push("");
  const measures = measureTokens();
  lines.push("export const measures = {");
  for (const [name, value] of Object.entries(measures)) {
    lines.push(`  ${safeKey(name)}: "${value}",`);
  }
  lines.push("} as const;");
  lines.push("");
  const spacingOpts = { ...DEFAULT_CONFIG.spacing, ...config.spacing };
  const spacingScale = generateSpacingScale({ baseUnit: spacingOpts.baseUnit });
  lines.push("export const spacing = {");
  for (const [name, entry] of spacingScale) {
    lines.push(`  ${safeKey(name)}: "${entry.rem === "0" ? "0" : entry.rem}",`);
  }
  lines.push("} as const;");
  lines.push("");
  const radiusScale = getBorderRadiusScale();
  lines.push("export const borderRadius = {");
  for (const [name, value] of Object.entries(radiusScale)) {
    lines.push(`  ${safeKey(name)}: "${value}",`);
  }
  lines.push("} as const;");
  lines.push("");
  const borderScale = getBorderScale();
  lines.push("export const border = {");
  for (const [name, value] of Object.entries(borderScale)) {
    lines.push(`  ${safeKey(name)}: "${value}",`);
  }
  lines.push("} as const;");
  lines.push("");
  const zIndexScale = getZIndexScale();
  lines.push("export const zIndex = {");
  for (const [name, value] of Object.entries(zIndexScale)) {
    lines.push(`  ${safeKey(name)}: ${value},`);
  }
  lines.push("} as const;");
  lines.push("");
  const shadowScale = generateShadowScale();
  lines.push("export const shadows = {");
  for (const shadow of shadowScale) {
    lines.push(`  ${safeKey(shadow.name)}: "${shadow.css}",`);
  }
  lines.push("} as const;");
  lines.push("");
  const durations = getDurationScale();
  lines.push("export const durations = {");
  for (const [name, ms] of Object.entries(durations)) {
    lines.push(`  ${safeKey(name)}: ${ms},`);
  }
  lines.push("} as const;");
  lines.push("");
  const easings = getEasingCurves();
  lines.push("export const easings = {");
  for (const name of Object.keys(easings)) {
    lines.push(`  ${safeKey(name)}: "${easingToCss(name)}",`);
  }
  lines.push("} as const;");
  lines.push("");
  const focus = getFocusRingConfig();
  const stateLayers = getStateLayerConfig();
  lines.push("export const interactive = {");
  lines.push(`  focusColor: "${focus.color}",`);
  lines.push(`  focusWidth: "${focus.width}px",`);
  lines.push(`  focusOffset: "${focus.offset}px",`);
  lines.push(`  hoverOpacity: ${stateLayers.hover},`);
  lines.push(`  focusOpacity: ${stateLayers.focus},`);
  lines.push(`  activeOpacity: ${stateLayers.active},`);
  lines.push(`  touchMin: "${getMinTouchTarget()}px",`);
  lines.push("} as const;");
  lines.push("");
  return lines.join(`
`) + `
`;
}
